// ALL SKIP STATEMENTS THAT AFFECT THIS SHADER!!!
// defined $LIGHTING_PREVIEW && defined $FASTPATH && $LIGHTING_PREVIEW && $FASTPATH

#pragma once
#include "shaderlib/cshader.h"
class hdn_screenspace_vs20_Static_Index
{
public:
	hdn_screenspace_vs20_Static_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_hdn_screenspace_vs20 1


class hdn_screenspace_vs20_Dynamic_Index
{
public:
	hdn_screenspace_vs20_Dynamic_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_hdn_screenspace_vs20 1

